version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: web
    ports:
      - "8080:8080"
    volumes:
      - ./web/index.html:/var/www/html/index.html
      - ./web/default:/etc/nginx/conf.d/default.conf

  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - ./proxy/default:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

