version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: web
    volumes:
      - ./web/index.html:/usr/share/nginx/html/index.html
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my_network

  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
